// AtlasForge service worker — generated by tools/build.mjs from tools/sw.template.js.
// Do not edit sw.js by hand.
//
// shell  — the app itself (HTML, CSS, JS, vendor libs, icons): precached on install,
//          served cache-first (every URL carries a content hash, so it never goes stale).
// data   — basemap GeoJSON (data/*.geojson, ~100 MB in total): cached the first time a
//          template is opened (or via "download for offline"), then served cache-first.
// A new version installs in the background and waits; the page asks the user to reload
// (message "skipWaiting") so an edit in progress is never interrupted.
const VERSION = "94877b8e34";
const SHELL = "af-shell-" + VERSION;
const DATA = "af-data-v1";
const PRECACHE = [
  "./",
  "build/app.js?v=77f3a75bbc",
  "build/chrome.js?v=1556233cb4",
  "build/map.js?v=69f36aa1f6",
  "build/objects.js?v=b54b70c214",
  "build/panels.js?v=f5a865a927",
  "build/world.js?v=9abdc5c1d3",
  "css/editor.css?v=741bd16019",
  "icons/apple-touch-icon.png",
  "icons/apple-touch-icon.png?v=953bc6d2b1",
  "icons/icon-192.png",
  "icons/icon-192.png?v=3be2bf771a",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "js/atlas.js?v=cc52d09ade",
  "js/core.js?v=36a0d3c188",
  "js/edit.js?v=bfb1feadc3",
  "js/export.js?v=a19bfd7ccc",
  "js/geo.js?v=a68a71e50b",
  "js/i18n.js?v=295420d344",
  "js/names.js?v=bba4c0ceee",
  "js/objects.js?v=22d08189ad",
  "js/pwa.js?v=9f35de276b",
  "js/regions.js?v=e79649b7ce",
  "js/storage.js?v=3b0efdbec5",
  "js/terrain-algos.js?v=cba7b01ecc",
  "js/terrain.worker.js?v=689563dd1a",
  "js/world.js?v=1c003c96e9",
  "manifest.webmanifest?v=10553cf767",
  "vendor/d3.min.js?v=69faba9d2f",
  "vendor/polygon-clipping.umd.min.js?v=6aa5a82c1d",
  "vendor/react-dom.production.min.js?v=7d4842a904",
  "vendor/react.production.min.js?v=e91b261662",
  "vendor/topojson-client.min.js?v=7561eb0097",
  "vendor/topojson-server.min.js?v=c10743095f",
  "vendor/topojson-simplify.min.js?v=7c24712513"
];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(SHELL).then((c) => c.addAll(PRECACHE)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith("af-shell-") && k !== SHELL).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (event) => {
  if (event.data === "skipWaiting") self.skipWaiting();
});

function isData(url) {
  return /\/data\/[^/]+\.(geo)?json$/.test(url.pathname);
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // the page itself: network first (quick updates), cached shell when offline
  if (req.mode === "navigate") {
    event.respondWith((async () => {
      try {
        const ctrl = new AbortController();
        const timer = setTimeout(() => ctrl.abort(), 4000);
        const res = await fetch(req, { signal: ctrl.signal });
        clearTimeout(timer);
        return res;
      } catch (e) {
        const cache = await caches.open(SHELL);
        return (await cache.match(req, { ignoreSearch: true })) || (await cache.match("./")) || Response.error();
      }
    })());
    return;
  }

  if (isData(url)) {
    event.respondWith((async () => {
      const cache = await caches.open(DATA);
      const hit = await cache.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok) cache.put(req, res.clone());
      return res;
    })());
    return;
  }

  event.respondWith((async () => {
    const hit = await caches.match(req);
    return hit || fetch(req);
  })());
});
